export const experianGjsonQuery = {
  customer:
    '{firstName:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.FirstName,lastName:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.LastName,genderCode:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.GenderCode,dob:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.DateOfBirthApplicant}',
  header:
    '{INProfileResponse.Header.SystemCode,INProfileResponse.Header.ReportDate,INProfileResponse.Header.ReportTime,INProfileResponse.Header.MessageText}',
  userMessage: 'INProfileResponse.UserMessage.UserMessageText',
  contact:
    '{telephone:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.TelephoneNumberApplicant,mobilePhone:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.MobilePhoneNumber}',
  emailId:
    'INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.EmailID',
  kyc: '{pan:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.IncomeTaxPAN,voterId:{id:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.VoterIdentityCard,expiryDate:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.VoterIDExpirationDate,issueDate:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.VoterIDIssueDate},passport:{id:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.PassportNumber,expiryDate:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.PassportExpirationDate,issueDate:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.PassportIssueDate},universalId:{id:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.UniversalIDNumber,expiryDate:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.UniversalIDExpirationDate,issueDate:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.UniversalIDIssueDate},rationCard:{id:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.RationCardNumber,expiryDate:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.RationCardExpirationDate,issueDate:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantDetails.RationCardIssueDate}}',
  employment:
    '{income:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentOtherDetails.Income,status:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentOtherDetails.EmploymentStatus,maritalStatus:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentOtherDetails.MaritalStatus}',
  address:
    '{address1:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantAdditionalAddressDetails,address2:INProfileResponse.CurrentApplication.CurrentApplicationDetails.CurrentApplicantAddressDetails}',
  accountSummary:
    '{totalAccount:INProfileResponse.CAISAccount.CAISSummary.CreditAccount.CreditAccountTotal,activeAccount:INProfileResponse.CAISAccount.CAISSummary.CreditAccount.CreditAccountTotal,accountDefault:INProfileResponse.CAISAccount.CAISSummary.CreditAccount.CreditAccount,accountClosed:INProfileResponse.CAISAccount.CAISSummary.CreditAccount.CreditAccountClosed,outstandingBalanceSecured:INProfileResponse.CAISAccount.CAISSummary.TotalOutstandingBalance.OutstandingBalanceSecured,outstandingBalanceUnsecured:INProfileResponse.CAISAccount.CAISSummary.TotalOutstandingBalance.OutstandingBalanceUnsecured,outstandingBalanceAll:INProfileResponse.CAISAccount.CAISSummary.TotalOutstandingBalance.OutstandingBalanceAll}',
  accounts:
    'INProfileResponse.CAISAccount.CAISAccountDetails.#.{memberName:SubscriberName,accountNumber:AccountNumber,type:AccountType,dateOpened:OpenDate,sanctionAmount:HighestCreditOrOriginalLoanAmount,frequency:TermsFrequency,paymentHistory1:PaymentHistoryProfile,currentBalance:CurrentBalance,dateReportedAndCertified:DateReported,lastPaymentDate:DateOfLastPayment,settlementAmount:SettlementAmount,collateralType:TypeOfCollateral,collateralValue:ValueOfCollateral,repaymentTenure:RepaymentTenure,accountHistory:CAISAccountHistory,SuitFiledWillfulDefault,SuitFiledWillfulDefaultWrittenOffStatus,dateClosed:DateClosed,CreditFacility,amountOverdue:AmountPastDue,creditLimit:CreditLimitAmount,repaymentTenure:RepaymentTenure,frequency:TermsFrequency,writtenOff:WrittenOffAmtTotal,rateOfInterest:RateOfInterest,writtenOffPrincipal:WrittenOffAmtPrincipal}',
  enquirySummary:
    '{last7Days:INProfileResponse.CAPS.CAPSSummary.CAPSLast7Days,last30Days:INProfileResponse.CAPS.CAPSSummary.CAPSLast30Days,last90Days:INProfileResponse.CAPS.CAPSSummary.CAPSLast90Days,last180Days:INProfileResponse.CAPS.CAPSSummary.CAPSLast180Days}',
  enquiry:
    'INProfileResponse.CAPS.CAPSApplicationDetails.#.{firstName:SubscriberName,date:DateOfRequest,reason:EnquiryReason,purpose:FinancePurpose,amount:AmountFinanced}',
  score: 'INProfileResponse.Score.BureauScore',
};

export const cibilGJsonQuery = {
  header:
    '{version:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.Header.Version,enquiryControlNumber:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.Header.EnquiryControlNumber,dateProcessed:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.Header.DateProcessed,timeProcessed:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.Header.TimeProcessed,memberCode:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.Header.MemberCode,reportNumber:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.Header.ReferenceNumber}',
  customer:
    '{name:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.NameSegment.ConsumerName1,dob:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.NameSegment.DateOfBirth,gender:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.NameSegment.Gender}',
  kyc: 'ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.IDSegment.#.{type:IDType,value:IDNumber,IssueDate,ExpirationDate}',
  contact:
    'ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.TelephoneSegment.#.{type:TelephoneType,value:TelephoneNumber,TelephoneExtension}',
  email:
    'ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.EmailContactSegment.#.EmailID',
  employment:
    '{occupation:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.EmploymentSegment.OccupationCode,accountType:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.EmploymentSegment.AccountType,date:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.EmploymentSegment.DateReportedCertified,netGross:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.EmploymentSegment.NetGrossIndicator,monthlyAnnual:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.EmploymentSegment.MonthlyAnnualIndicator,income:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.EmploymentSegment.Income}',
  score:
    'ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.ScoreSegment.#(ScoreName=="CIBILTUSC3").{value:Score,date:ScoreDate,ReasonCode1,ReasonCode2,ReasonCode3,ReasonCode4,ReasonCode5}',
  address:
    'ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.Address.#.{line1:AddressLine1,line2:AddressLine2,line3:AddressLine3,line4:AddressLine4,line5:AddressLine5,state:StateCode,pincode:PinCode,category:AddressCategory,residence:ResidenceCode,dateReported:DateReported,enrichedThroughEnquiry:EnrichedThroughEnquiry}',
  account:
    'ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.Account.#.AccountNonSummarySegmentFields',
  enquiry:
    'ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.BureauResponseXml.CreditReport.Enquiry.#.{date:DateOfEnquiryFields,firstName:EnquiringMemberShortName,purpose:EnquiryPurpose,amount:EnquiryAmount}',
  secondaryReport:
    '{header:{version:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.Header.Version,reportNumber:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.Header.ReferenceNumber,memberCode:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.Header.MemberCode,enquiryControlNumber:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.Header.EnquiryControlNumber,dateProcessed:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.Header.DateProcessed,timeProcessed:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.Header.TimeProcessed},customer:{firstName:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.NameSegment.ConsumerName1,dob:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.NameSegment.DateOfBirth,gender:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.NameSegment.Gender},kyc:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.IDSegment.#.{type:IDType,value:IDNumber,IssueDate,ExpirationDate},contact:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.TelephoneSegment.#.{type:TelephoneType,value:TelephoneNumber,TelephoneExtension},email:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.EmailContactSegment.#.EmailID,address:ContextData.Field.0.Applicants.Applicant.DsCibilBureau.Response.CibilBureauResponse.SecondaryReportXml.Root.CreditReport.Address.#.{line1:AddressLine1,line2:AddressLine2,line3:AddressLine3,line4:AddressLine4,line5:AddressLine5,state:StateCode,pincode:PinCode,category:AddressCategory,residence:ResidenceCode,dateReported:DateReported,enrichedThroughEnquiry:EnrichedThroughEnquiry}}',
};
