export const financePurpose: Record<number, string> = {
  1: 'Agricultural Machinery',
  2: 'Animal Husbandry',
  3: 'Aquaculture',
  4: 'Biogas Plant',
  5: 'Crop Loan',
  6: 'Horticulture',
  7: 'Irrigation System',
  8: 'New Car',
  9: 'Overdraft against Car',
  10: 'Used Car',
  11: 'General',
  12: 'Small & Medium Business',
  13: 'Professionals',
  14: 'Trade',
  15: 'Bus',
  16: 'Tempo',
  17: 'Tipper',
  18: 'Truck ',
  20: 'Forklift',
  21: 'Wheel Loaders',
  22: 'Consumer Search',
  66: 'Consumer Search Loan',
  68: 'Consumer Search Loan',
  23: 'Credit Card',
  24: 'Fleet Card',
  25: 'For Working Executives',
  26: 'Study Abroad',
  27: 'Study in India',
  28: 'Leasing',
  29: 'Bank Deposits',
  30: 'Gold',
  31: 'Govt. Bonds / PPF / NSC / KVP / FD',
  32: 'Shares and Mutual Funds',
  33: 'Business Loan',
  34: 'Housing Loan',
  35: 'Personal Loan',
  36: 'Agriculture',
  37: 'General',
  38: 'Small Business',
  39: 'Computers / Laptops',
  40: 'Consumer Durables',
  41: 'Marriage / Religious Ceremonies',
  43: 'Balance Transfer',
  44: 'Home Improvement / Extension',
  45: 'Land',
  46: 'Lease Rental Discounting',
  47: 'Loan against Property',
  48: 'New Home',
  49: 'Office Premises',
  50: 'Under construction',
  99: 'Others',
};

export const loanTypeMapExp: Record<number, string> = {
  0: 'Other',
  1: 'Auto Loan(Personal)',
  2: 'Housing Loan',
  3: 'Property Loan',
  4: 'Loan against Shares/Securities',
  5: 'Personal Loan',
  6: 'Consumer Loan',
  7: 'Gold Loan',
  8: 'Educational Loan',
  9: 'Loan to Professional',
  10: 'Credit Card',
  11: 'Leasing',
  12: 'Overdraft',
  13: 'Two-Wheeler Loan',
  14: 'Non-funded Credit Facility',
  15: 'Loan against Bank Deposits',
  16: 'Fleet Card',
  17: 'Commercial Vehicle Loan',
  18: 'Telco - Wireless',
  19: 'Telco - Broadband',
  20: 'Telco - Landline',
  31: 'Secured Credit Card',
  32: 'Used Car Loan',
  33: 'Construction Equipment Loan',
  34: 'Tractor Loan',
  35: 'Corporate Credit Card',
  36: 'Kisan Credit Card',
  37: 'Loan on Credit Card',
  38: 'Prime Minister Jan Dhan Yojana - Overdraft',
  39: 'Mudra Loans - Shishu / Kishor / Tarun',
  43: 'Microfinance - Others',
  44: 'Pradhan Mantri Awas Yojana - Credit Link Subsidy Scheme MAY CLSS',
  45: 'P2P Personal Loan',
  46: 'P2P Auto Loan',
  47: 'P2P Education Loan',
  51: 'Business Loan - General',
  52: 'Business Loan - Priority Sector - Small Business',
  53: 'Business Loan - Priority Sector - Agriculture',
  54: 'Business Loan - Priority Sector - Others',
  55: 'Business Non-Funded Credit Facility - General',
  56: 'Business Non-Funded Credit Facility - Priority Sector - Small Business',
  57: 'Business Non-Funded Credit Facility - Priority Sector - Agriculture',
  58: 'Business Non-Funded Credit Facility - Priority Sector - Others',
  59: 'Business Loans against Bank Deposits',
  60: 'Staff Loan',
  61: 'Business Loan - Unsecured',
  NaN: '-',
};

export const loanTypeMapCibil: Record<number, string> = {
    0: "Other", 
    1: "Auto Loan(Personal)",
    2: "Housing Loan",
    3: "Property Loan",
    4: "Loan against Shares/Securities",
    5: "Personal Loan",
    6: "Consumer Loan",
    7: "Gold Loan",
    8: "Educational Loan",
    9: "Loan to Professional",
    10: "Credit Card",
    11: "Leasing",
    12: "Overdraft",
    13: "Two-Wheeler Loan",
    14: "Non-funded Credit Facility",
    15: "Loan against Bank Deposits",
    16: "Fleet Card",
    17: "Commercial Vehicle Loan",
    18: "Telco - Wireless",
    19: "Telco - Broadband",
    20: "Telco - Landline",
    31: "Secured Credit Card",
    32: "Used Car Loan",
    33: "Construction Equipment Loan",
    34: "Tractor Loan",
    35: "Corporate Credit Card",
    36: "Kisan Credit Card",
    37: "Loan on Credit Card",
    38: "Prime Minister Jan Dhan Yojana - Overdraft",
    39: "Mudra Loans - Shishu / Kishor / Tarun",
    43: "Microfinance - Others",
    51: "Business Loan - General",
    52: "Business Loan - Priority Sector - Small Business",
    53: "Business Loan - Priority Sector - Agriculture",
    54: "Business Loan - Priority Sector - Others",
    55: "Business Non-Funded Credit Facility - General",
    56: "Business Non-Funded Credit Facility - Priority Sector - Small Business",
    57: "Business Non-Funded Credit Facility - Priority Sector - Agriculture",
    58: "Business Non-Funded Credit Facility - Priority Sector - Others",
    59: "Business Loans against Bank Deposits",
    60: "Staff Loan",
    61: "Business Loan - Unsecured",
    80: "Microfinance Detailed Report",
    81: "Summary Report",
    88: "Locate Plus for Insurance",
    90: "Account Review",
    91: "Retro Enquiry",
    92: "Locate Plus",
    97: "Adviser Liability",
    98: "Secured",
    99: "Unsecured",
    NaN: '-',
};


export const idTypeMap: Record<number, string> = {
  1: 'PAN',
  2: 'Passport Number',
  3: 'Voter ID Number',
  4: 'Driver’s License Number',
  5: 'Ration Card Number',
  6: 'Universal ID Number (UID)',
};

export const idTypeReverseMap = {
  pan: '01',
  passport: '02',
  voter_id: '03',
  driver_license: '04',
  ration_card: '05',
  uid: '06',
};
export const telephoneTypeMap: Record<number, string> = {
  1: 'Mobile Phone',
  2: 'Home Phone',
  3: 'Office Phone',
  0: 'Not Classified',
};

export const telephoneReverseTypeMap = {
  mobile: '01',
  home: '02',
  office: '03',
  not_classified: '00',
};

export const addressTypeMap: Record<number, string> = {
  1: 'Permanent Address',
  2: 'Residence Address',
  3: 'Office Address',
  4: 'Not Categorized',
};
export const occupationMap: Record<number, string> = {
  1: 'Salaried',
  2: 'Self Employed Professional',
  3: 'Self Employed',
  4: 'Others',
};

export const reasonCodeMap: Record<number, string> = {
  1: 'LOW CREDIT AGE',
  2: 'PRESENCE OF DELINQUENCY IN LAST 12 MONTHS',
  3: 'PRESENCE OF DELINQUENCY IN THE RECENT PAST',
  4: 'LOW PROPORTION OF SATISFACTORY TRADES',
  5: 'SUPPRESS',
  6: 'HIGH BALANCE BUILD-UP ON SECURED LOANS',
  7: 'PRESENCE OF DELINQUENCY',
  8: 'PRESENCE OF SEVERE DELINQUENCY AS OF RECENT UPDATE',
  9: 'HIGH BALANCE BUILD-UP',
  10: 'SUPPRESS',
  11: 'PRESENCE OF DELINQUENCY',
  12: 'PRESENCE OF DELINQUENCY AS OF RECENT UPDATE',
  13: 'SUPPRESS',
  14: 'INCREASE IN NON-MORTGAGE INDEBTEDNESS IN LAST 12 MONTHS',
  15: 'INCREASE IN NON-MORTGAGE INDEBTEDNESS IN LAST 3 MONTHS',
  16: 'HIGH BALANCE BUILD-UP',
  17: 'SUPPRESS',
  18: 'HIGH OUTSTANDING BALANCE',
  19: 'INCREASE IN NON-MORTGAGE INDEBTEDNESS IN LAST 12 MONTHS',
  20: 'LENGTH OF TIME SINCE SEVERE DELINQUENCY IS TOO SHORT',
  21: 'LOW PROPORTION OF SATISFACTORY TRADES',
  22: 'PRESENCE OF DELINQUENCY',
  23: 'SUPPRESS',
  24: 'LOW CREDIT AGE',
  25: 'HIGH BALANCE BUILD-UP ON NON-MORTGAGE LOANS',
  26: 'PRESENCE OF SEVERE DELINQUENCY',
  27: 'PRESENCE OF HIGH CREDIT ACTIVITY (INQUIRIES)',
  28: 'LOW CREDIT AGE',
  29: 'PRESENCE OF DELINQUENCY',
  30: 'LENGTH OF TIME SINCE MODERATE TO SEVERE DELINQUENCY IS TOO SHORT',
  31: 'PRESENCE OF DELINQUENCY',
  32: 'PRESENCE OF DELINQUENCY',
  33: 'HIGH PROPORTION OF DELINQUENT TRADES',
  34: 'SUPPRESS',
  35: 'PRESENCE OF DELINQUENCY',
  36: 'HIGH BALANCE BUILD-UP ON REVOLVING TRADES',
  37: 'PRESENCE OF DELINQUENCY AS OF RECENT UPDATE',
  38: 'RECENT HIGH BALANCE BUILD ON BANKCARD TRADES',
  39: 'HIGH PROPORTION OF OUTSTANDING TRADES',
  40: 'HIGH BALANCE IN PROPORTION TO HIGH CREDIT AMOUNT IN THE LAST 12 MONTHS',
  41: 'PAYMENT MADE IN PROPORTION TO TOTAL CARD BALANCE OUTSTANDING IS LOW',
  42: 'PAYMENT MADE IN PROPORTION TO TOTAL BALANCE OUTSTANDING IS LOW',
  43: 'SUPPRESS',
  44: 'SUPPRESS',
  45: 'HIGH BALANCE BUILD-UP ON NON-MORTGAGE LOANS IN PAST 6 MONTHS',
  46: 'HIGH BALANCE BUILD-UP ON UNSECURED LOANS',
  47: 'SUPPRESS',
  48: 'SUPPRESS',
  49: 'PRESENCE OF DELINQUENCY AS OF RECENT UPDATE',
  50: 'SUPPRESS',
  51: 'SUPPRESS',
  52: 'PRESENCE OF MINOR DELINQUENCY IN LAST 24 MONTHS',
  53: 'PRESENCE OF SEVERE DELINQUENCY IN LAST 12 MONTHS',
  54: 'CREDIT AGE LESS THAN SIX MONTHS',
};

export const ownershipIndicatorTypeMap: Record<number, string> = {
  1: 'Individual',
  2: 'Authorised User',
  3: 'Guarantor',
  4: 'Joint',
};

export const stateMappings: Record<number, string> = {
    0: "-",
    1: "Jammu & Kashmir",
    2: "Himachal Pradesh",
    3: "Punjab",
    4: "Chandigarh",
    5: "Uttaranchal/Uttarakhand",
    6: "Haryana",
    7: "Delhi",
    8: "Rajasthan",
    9: "Uttar Pradesh",
    10: "Bihar",
    11: "Sikkim",
    12: "Arunachal Pradesh",
    13: "Nagaland",
    14: "Manipur",
    15: "Mizoram",
    16: "Tripura",
    17: "Meghalaya",
    18: "Assam",
    19: "West Bengal",
    20: "Jharkhand",
    21: "Orissa",
    22: "Chhattisgarh",
    23: "Madhya Pradesh",
    24: "Gujarat",
    25: "Daman & Diu",
    26: "Dadra & Nagar Haveli and Daman & Diu",
    27: "Maharashtra",
    28: "Andhra Pradesh",
    29: "Karnataka",
    30: "Goa",
    31: "Lakshadweep",
    32: "Kerala",
    33: "Tamil Nadu",
    34: "Pondicherry",
    35: "Andaman & Nicobar Islands",
    36: "Telangana",
    38: "Ladakh",
}

export const collateralTypes:Record<string,string> = {
    "00": "No Collateral",
    "01": "Property",
    "02": "Gold",
    "03": "Shares",
    "04": "Saving Account and Fixed Deposit",
    "05": "Multiple Securities",
    "06": "Others"
}

export const genderCodeMapCibil = {
  '1': 'Female',
  '2': 'Male',
  '3': 'Transgender',
};

export const genderCodeMapExperian = {
  '1': 'Male',
  '2': 'Female',
  '3': 'Transgender',
};
