version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apollo
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 120
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 900
      runas: root

ValidateService:
  - location: scripts/bootup.sh
    timeout: 200
    runas: root
