# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

env:
  exported-variables:
    - EnvType
  parameter-store:
    API_GATEWAY: 'ApiGatewayInternalProxyApiURL'
    NEXT_PUBLIC_USER_POOL_CLIENT_ID: 'APOLLO-CLIENT-ID'
    NEXT_PUBLIC_USER_POOL_ID: 'APOLLO-USER-POOLID'
    COGNITO_REGION: 'COGNITO-REGION'
    APOLLO_BASE_URL: 'APOLLO-BASE-URL'
    PUBLIC_ENV_DOMAIN: 'ENV_DOMAIN'
    NEXT_PUBLIC_COGNITO_DOMAIN: 'APOLLO-COGNITO-DOMAIN'

  secrets-manager:
    BASIC_AUTH: 'BasicAuthToken-Secrets:token'
    MIXPANEL_TOKEN: 'Mixpanel-Secrets:ProjectToken'
    DatadogAppId: 'DatadogLicense:ApolloAppID'
    DatadogClientToken: 'DatadogLicense:ApolloClientToken'
    CodeArtifactDomain: 'Npm-Config:CODE_ARTIFACT_DOMAIN'
    CodeArtifactDomainOwner: 'Npm-Config:DOMAIN_OWNER_ACCOUNT_ID'
    CodeArtifactGroupRepo: 'Npm-Config:CODE_ARTIFACT_GROUP_REPO'

# https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching
#cache:
#  paths:
#    - 'node_modules/**/*' # Cache `node_modules` for faster `yarn` or `npm i`
#    - '.next/cache/**/*' # Cache Next.js build files
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "hello"
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - echo "install phase"
      - echo "pre build phase"
      - aws codeartifact login --tool npm --domain ${CodeArtifactDomain} --domain-owner ${CodeArtifactDomainOwner} --repository ${CodeArtifactGroupRepo}

  build:
    commands:
      - node -v
      - npm -v
      - npm install -g yarn --silent --no-progress
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn cache clean
      - yarn install
      - |
        cat > .env <<EOF
        NEXT_PUBLIC_DATADOG_APPID=${DatadogAppId}
        NEXT_PUBLIC_DATADOG_CLIENT_TOKEN=${DatadogClientToken}
        SHIELD_SERVER=${API_GATEWAY}shield/api/v1/
        ROGUE_SERVER=${API_GATEWAY}rogue/api/v1/
        SCARLET_SERVER=${API_GATEWAY}scarlet/api/v1/
        VISION_SERVER=${API_GATEWAY}vision/api/v1/
        HULK_SERVER=${API_GATEWAY}hulk/api/v1/
        DR_STRANGE_SERVER=${API_GATEWAY}drstrange/api/v1/
        BUREAU_ENGINE_SERVER=${API_GATEWAY}bureauengine/
        LOGAN_SERVER=${API_GATEWAY}logan/api/v1/
        ANTMAN_LAMBDAS=${API_GATEWAY}antman/
        CHRONOS_SERVER=${API_GATEWAY}chronos/api/v1/
        TARS_SERVER=${API_GATEWAY}tars/api/v1/
        SPIDERMAN_SERVER=${API_GATEWAY}spiderman/api/v1/
        GROOT_SERVER=${API_GATEWAY}groot/api/v1/
        THANOS_SERVER=${API_GATEWAY}thanos/api/v1/
        CEREBRO_SERVER=${API_GATEWAY}cerebro/api/
        LANNISTER_SERVER=${API_GATEWAY}lannister/api/v1/
        BATMAN_SERVER=${API_GATEWAY}batman/api/v1/
        DARWIN_SERVER=${API_GATEWAY}darwin/api/v1/
        HEIMDALL_SERVER=${API_GATEWAY}heimdall/api/v1/
        EYWA_SERVER=${API_GATEWAY}eywa/api/v1/
        GAMORA_SERVER=${API_GATEWAY}gamora/api/v1/
        HERA_SERVER=${API_GATEWAY}hera/api/v1/
        SCROOGE_SERVER=${API_GATEWAY}scrooge/api/v1/
        MORPHEUS_SERVER=${API_GATEWAY}morpheus/api/v1/
        XMEN_SERVER=${API_GATEWAY}xmen/api/v1/
        ASGARD_SERVER=${API_GATEWAY}asgard/api/v1/
        DEADPOOL_SERVER=${API_GATEWAY}deadpool/api/
        ANTMAN_SERVER=https://antman.${PUBLIC_ENV_DOMAIN}/api/v1/
        DEATHLOK_SERVER=${API_GATEWAY}deathlok/api/v1/
        NEBULA_SERVER=${API_GATEWAY}nebula/api/v1/
        MJOLNIR_SERVER=${API_GATEWAY}mjolnir/api/v1/
        BIFROST_SERVER=${API_GATEWAY}bifrost/api/v1/
        STORM_SERVER=${API_GATEWAY}storm/api/v1/
        KAIZEN_SERVER=${API_GATEWAY}kaizen/api/v1/
        CHARIZARD_SERVER=${API_GATEWAY}charizard/api/v1/
        AURORA_SERVER=${API_GATEWAY}aurora/api/v1/
        POSEIDON_SERVER=${API_GATEWAY}poseidon/api/v1/
        VPAYOUT_SERVER=${API_GATEWAY}vpayout/api/v1/
        SILVERSURFER_SERVER=${API_GATEWAY}silversurfer/api/v1/

        BASIC_AUTH=${BASIC_AUTH}
        USE_BASIC_AUTH=false
        NEXT_PUBLIC_USER_POOL_CLIENT_ID=${NEXT_PUBLIC_USER_POOL_CLIENT_ID}
        NEXT_PUBLIC_USER_POOL_ID=${NEXT_PUBLIC_USER_POOL_ID}
        COGNITO_REGION=${COGNITO_REGION}
        NEXT_PUBLIC_REDIRECT_SIGN_IN_URL=${APOLLO_BASE_URL}/login
        NEXT_PUBLIC_REDIRECT_SIGN_IN_URL_LOCAL=http://localhost:3000/login
        NEXT_PUBLIC_REDIRECT_SIGN_OUT_URL_LOCAL=http://localhost:3000/logout
        NEXT_PUBLIC_REDIRECT_SIGN_OUT_URL=${APOLLO_BASE_URL}/logout
        NEXT_PUBLIC_COGNITO_DOMAIN=${NEXT_PUBLIC_COGNITO_DOMAIN}
        NEXT_PUBLIC_API_URL=${APOLLO_BASE_URL}
        FETCH_USER_ROLE_FOR_ADMIN=qcadmin
        NEW_RELIC_LOG_ENABLED=false
        MIXPANEL_TOKEN=${MIXPANEL_TOKEN}
        ENV_TYPE=${EnvType}
        NEXT_PUBLIC_ENV_TYPE=${EnvType}
        NEXT_PUBLIC_APP_VERSION=${CODEBUILD_RESOLVED_SOURCE_VERSION}
        EOF
      - cat .env
      - rm -rf .next
      - yarn build
      - rm -rf node_modules .cache .yarn
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*'
